name: sterlingz
favicon: null
layout_spectrum: 0.8460350665263832
typography_spectrum: 0.3998797107487917
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.09376802644692361
  lightness: 0.48408163478598
  saturation: 0.4340476857032627
  rhythmicContrast: 0.2794499632436782
purpose: []
